export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
export const REMOVE_FROM_FAVOURITE = "REMOVE_FROM_FAVOURITE";
export const SEARCH_CHANNEL = "SET_SEARCH_CHANNEL";
export const SET_CHANNEL_DATA = "SET_CHANNEL_DATA";
export const SET_VIDEOS_LIST = "SET_VIDEOS_LIST";




