export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
export const REMOVE_FROM_FAVOURITE = "REMOVE_FROM_FAVOURITE";
export const SEARCH_CHANNEL = "SET_SEARCH_CHANNEL";
export const SET_CHANNEL_DATA = "SET_CHANNEL_DATA";
export const SET_VIDEOS_LIST = "SET_VIDEOS_LIST";
export const SET_SIDEBAR_SHOW = "SET_SIDEBAR_SHOW";


export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL";
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST";


export const GET_SELECTED_VIDEO = "GET_SELECTED_VIDEO";
export const SELECTED_VIDEO_REQUEST = "SELECTED_VIDEO_REQUEST";
export const SELECTED_VIDEO_SUCCESS = "SELECTED_VIDEO_SUCCESS";
export const SELECTED_VIDEO_FAIL = "SELECTED_VIDEO_FAIL";


export const GET_CHANNEL_DETAILS_OF_SELECTED_VIDEO = "GET_CHANNEL_DETAILS_OF_SELECTED_VIDEO";
export const CHANNEL_DETAILS_REQUEST_OF_SELECTED_VIDEO = "CHANNEL_DETAILS_REQUEST_OF_SELECTED_VIDEO";
export const CHANNEL_DETAILS_SUCCESS_OF_SELECTED_VIDEO = "CHANNEL_DETAILS_SUCCESS_OF_SELECTED_VIDEO";
export const CHANNEL_DETAILS_FAIL_OF_SELECTED_VIDEO = "CHANNEL_DETAILS_FAIL_OF_SELECTED_VIDEO";


export const COMMENTS_REQUEST_OF_SELECTED_VIDEO = "COMMENTS_REQUEST_OF_SELECTED_VIDEO";
export const COMMENTS_SUCCESS_OF_SELECTED_VIDEO = "COMMENTS_SUCCESS_OF_SELECTED_VIDEO";
export const COMMENTS_FAIL_OF_SELECTED_VIDEO = "COMMENTS_FAIL_OF_SELECTED_VIDEO";


export const GET_RELATED_VIDEOS_OF_SELECTED_VIDEO = "GET_RELATED_VIDEOS_OF_SELECTED_VIDEO";
export const RELATED_VIDEOS_REQUEST_OF_SELECTED_VIDEO = "RELATED_VIDEOS_REQUEST_OF_SELECTED_VIDEO";
export const RELATED_VIDEOS_SUCCESS_OF_SELECTED_VIDEO = "RELATED_VIDEOS_SUCCESS_OF_SELECTED_VIDEO";
export const RELATED_VIDEOS_FAIL_OF_SELECTED_VIDEO = "RELATED_VIDEOS_FAIL_OF_SELECTED_VIDEO";


export const GET_SEARCH_VIDEOS = "GET_SEARCH_VIDEOS";
export const SEARCH_VIDEOS_REQUEST = "SEARCH_VIDEOS_REQUEST";
export const SEARCH_VIDEOS_SUCCESS = "SEARCH_VIDEOS_SUCCESS";
export const SEARCH_VIDEOS_FAIL = "SEARCH_VIDEOS_FAIL";


export const GET_CHANNEL_VIDEOS = "GET_SEARCH_VIDEOS";
export const CHANNEL_VIDEOS_REQUEST = "CHANNEL_VIDEOS_REQUEST";
export const CHANNEL_VIDEOS_SUCCESS = "CHANNEL_VIDEOS_SUCCESS";
export const CHANNEL_VIDEOS_FAIL = "CHANNEL_VIDEOS_FAIL";


export const GET_VIDEOS_BY_CATEGORY = "GET_VIDEOS_BY_CATEGORY";
// export const CATEGORY_VIDEOS_REQUEST = "CATEGORY_VIDEOS_REQUEST";
// export const CATEGORY_VIDEOS_SUCCESS = "CATEGORY_VIDEOS_SUCCESS";
// export const CATEGORY_VIDEOS_FAIL = "CATEGORY_VIDEOS_FAIL";


export const GET_LOGIN = "GET_LOGIN";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOAD_USER_DATA = "LOAD_USER_DATA";


export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";


export const GET_SUBSCRIPTIONS = "GET_SUBSCRIPTIONS";
export const SUBSCRIPTIONS_REQUEST = "SUBSCRIPTIONS_REQUEST";
export const SUBSCRIPTIONS_SUCCESS = "SUBSCRIPTIONS_SUCCESS";
export const SUBSCRIPTIONS_FAIL = "SUBSCRIPTIONS_FAIL";












